name: default

on:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: 'anilist'
  PROJECT_ID: integral-zephyr-481413-k6
  AR_REPO_LOCATION: 'us-west1'
  AR_URL: 'us-west1-docker.pkg.dev/integral-zephyr-481413-k6/dev'
  SERVICE_ACCOUNT: 'github-actions-service-account@integral-zephyr-481413-k6.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/761028433156/locations/global/workloadIdentityPools/my-app-dev-pool/providers/github-actions-provider'

jobs:
  provision:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build -x test
      - name: Google Auth
        id: auth
        uses: ./.github/actions/gcp-auth
      - name: "Debug"
        run: echo ${{ steps.auth.outputs.access_token }}
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.AR_REPO_LOCATION }}-docker.pkg.dev'
      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" ./
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: provision
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
      - name: Image name
        run:  echo "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
      - name: Deploy
        run: |
              gcloud run deploy anilist \
                --region us-west1 \
                --project ${{ env.PROJECT_ID }} \
                --image "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" \
                --set-secrets "DATASOURCE_USERNAME=db-username:latest,DATASOURCE_PASSWORD=db-password:latest" \
                --quiet